"$schema" = "https://starship.rs/config-schema.json"
add_newline = true
format = "$all"
scan_timeout = 10

[character]
error_symbol = "[ï„…](bold red)[ï„…](bold green)[ï„…](bold yellow)"
success_symbol = "[ï„…](bold red)[ï„…](bold green)[ï„…](bold yellow)"

[nix_shell]
disabled = false
format = "via [â˜ƒï¸ $state( ($name))](bold blue) "
impure_msg = "[impure shell](bold red)"
pure_msg = "[pure shell](bold green)"
symbol = "ï‹œ "
unknown_msg = "[unknown shell](bold yellow)"

[package]
disabled = true

[sudo]
disabled = true
style = "bold green"
symbol = "ğŸ§™ "
